name: Build and push image
on:
  schedule:
    - cron: '* * * * 0'
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: blmhemu/caddy:latest
