name: Build and push image
on:
  release:
    types: [published]
  push:
    branches:
      - 'main'
      - 'master'
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build push Docker images
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: blmhemu/caddy:$${{ github.event.release.tag_name || 'latest' }}
